import { useEffect, useState } from 'react'
import { ArrowDown, ArrowDownRight, ArrowRight, ArrowUpRight, Check, Code2, Download, Github, GraduationCap, Mail, Menu, Moon, Sun, X } from 'lucide-react'
import { achievements, certifications, education, experience, profile, skillGroups } from './data/profile'
import { projects } from './data/projects'

const links = [['About','about'],['Experience','experience'],['Projects','projects'],['Skills','skills'],['Education','education'],['Certifications','certifications'],['Contact','contact']]
const socials = [{name:'GitHub',href:profile.github,Icon:Github},{name:'LinkedIn',href:profile.linkedin,Icon:ArrowUpRight},{name:'LeetCode',href:profile.leetcode,Icon:Code2}]
const ext = {target:'_blank',rel:'noreferrer'} as const

export default function App() {
  const [dark,setDark]=useState(()=>localStorage.getItem('portfolio-theme')==='dark')
  const [menu,setMenu]=useState(false)
  const [sent,setSent]=useState(false)
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('portfolio-theme',dark?'dark':'light')},[dark])
  function send(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const subject=encodeURIComponent(`Portfolio message from ${f.get('name')}`);const body=encodeURIComponent(`From: ${f.get('name')} (${f.get('email')})\n\n${f.get('message')}`);location.href=`mailto:${profile.email}?subject=${subject}&body=${body}`;setSent(true)}
  return <div className="site-shell">
    <header className="nav-wrap"><nav className="nav container" aria-label="Main navigation"><a className="wordmark" href="#home" onClick={()=>setMenu(false)}><span className="mark">S.</span>Satyam Anand</a><div className={`nav-links ${menu?'open':''}`}>{links.map(([n,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{n}</a>)}<div className="mobile-social"><a href={profile.github} {...ext}>GitHub ↗</a><a href={profile.linkedin} {...ext}>LinkedIn ↗</a></div></div><div className="nav-actions"><a className="nav-resume" href="/resume.docx" download="Satyam-Anand-Resume.docx"><Download size={14}/> Resume</a><button className="theme-toggle" onClick={()=>setDark(!dark)} aria-label={`Switch to ${dark?'light':'dark'} mode`}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label={menu?'Close menu':'Open menu'}>{menu?<X/>:<Menu/>}</button></div></nav></header>
    <main>
      <section className="hero container" id="home"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> COMPUTER SCIENCE · AI/ML</div><p className="hero-intro">Hi, I'm <span>Satyam Anand.</span></p><h1>Building thoughtful software<br className="desktop-break"/> with <em>AI at the core.</em></h1><p className="hero-role">{profile.role}</p><p className="hero-description">{profile.summary}</p><div className="hero-ctas"><a className="button primary" href="#projects">View Projects <ArrowDownRight size={17}/></a><a className="button secondary" href="/resume.docx" download="Satyam-Anand-Resume.docx"><Download size={16}/> Download Resume</a></div><div className="hero-social">{socials.map(({name,href,Icon})=><a key={name} href={href} {...ext}><Icon size={16}/>{name}<ArrowUpRight size={13}/></a>)}<a href={`mailto:${profile.email}`}><Mail size={16}/>Email<ArrowUpRight size={13}/></a></div></div>
        <div className="hero-art" aria-label="Areas of focus"><div className="art-top"><span className="window-dots"><b/><b/><b/></span><span>satya.py</span><span className="art-live"><i/> BUILDING</span></div><div className="code-card"><div className="line-no">01<br/>02<br/>03<br/>04<br/>05<br/>06<br/>07</div><div className="code-content"><p><span className="code-purple">class</span> <span className="code-green">Builder</span>:</p><p className="indent"><span className="code-purple">def</span> <span className="code-blue">focus</span>(self):</p><p className="indent2"><span className="code-muted"># turning ideas into systems</span></p><p className="indent2">skills = [</p><p className="indent3"><span className="code-orange">"AI/ML"</span>, <span className="code-orange">"RAG"</span>,</p><p className="indent3"><span className="code-orange">"LLMs"</span>, <span className="code-orange">"Data"</span>,</p><p className="indent2">]</p><p className="indent2"><span className="code-purple">return</span> skills</p></div></div><div className="art-chips"><span>PYTHON</span><span>AI / ML</span><span>RAG + LLMs</span><span>DATA ANALYTICS</span><span>DSA</span></div><div className="art-footer"><span>Building with curiosity</span><span>Portfolio · 2026</span></div><div className="art-orb orb-one"/><div className="art-orb orb-two"/></div><a className="scroll-cue" href="#about"><span>SCROLL TO EXPLORE</span><ArrowDown size={14}/></a></section>
      <section className="section about-section" id="about"><div className="container"><Head index="01" eyebrow="A LITTLE ABOUT ME" title="Curious by nature." accent="Builder by choice."/><div className="about-grid"><p className="about-lead">I like turning complex problems into <span>useful, human-centered tools.</span></p><div className="about-copy"><p>From intelligent travel planning to analytics and productivity tools, my projects are a place to learn by building. I’m interested in practical software and AI that makes everyday workflows better.</p><div className="about-focus">{['Python','AI/ML','RAG','LLM Integration','Data Analytics','DSA','System Design','SQL'].map(x=><span key={x}>{x}</span>)}</div></div></div></div></section>
      <section className="section experience-section" id="experience"><div className="container"><Head index="02" eyebrow="WHERE I'VE CONTRIBUTED" title="Experience &" accent="leadership."/><div className="timeline">{experience.map((item,i)=><article className="timeline-item" key={item.role}><div className="timeline-index">0{i+1}<span/></div><div className="timeline-card"><div className="timeline-heading"><div><h3>{item.role}</h3><p className="organization">{item.org}</p></div>{item.date&&<span className="date-label">{item.date}</span>}</div><p className="timeline-detail">{item.detail}</p>{item.tags&&<div className="tag-list">{item.tags.map(t=><span key={t}>{t}</span>)}</div>}</div></article>)}</div></div></section>
      <section className="section projects-section" id="projects"><div className="container"><Head index="03" eyebrow="SELECTED WORK" title="Things I've" accent="built."/><div className="project-grid">{projects.map((p,i)=><article className="project-card" key={p.title}><div className="project-visual"><div className={`project-art art-${i+1}`}><div className="visual-window"><div className="visual-bar"><i/><i/><i/><span>{['trip-planner','sales-insights','daylight.app'][i]}</span></div>{i===0?<Trip/>:i===1?<Chart/>:<Planner/>}</div><span className="project-number">0{i+1}</span></div></div><div className="project-body"><div className="project-meta"><span>{p.kind}</span><ArrowUpRight size={15}/></div><h3>{p.title}</h3><p className="project-description">{p.description}</p><div className="project-features">{p.features.map(f=><span key={f}><Check size={13}/>{f}</span>)}</div>{'note' in p&&<p className="project-note">{p.note}</p>}<div className="technology-list">{p.technologies.map(t=><span key={t}>{t}</span>)}</div><div className="project-links">{p.github?<a href={p.github} {...ext}><Github size={15}/> GitHub <ArrowUpRight size={13}/></a>:<span className="placeholder-link"><Github size={15}/> GitHub <small>[ADD GITHUB URL]</small></span>}{p.demo?<a href={p.demo} {...ext}>Live Demo <ArrowUpRight size={13}/></a>:<span className="placeholder-link">Live Demo <small>[ADD LIVE DEMO URL]</small></span>}</div></div></article>)}</div><div className="more-projects">More Projects <span>—</span> <a href={profile.github} {...ext}>Explore GitHub <ArrowUpRight size={14}/></a></div></div></section>
      <section className="section skills-section" id="skills"><div className="container"><Head index="04" eyebrow="MY TOOLKIT" title="Skills &" accent="technologies."/><div className="skills-grid">{Object.entries(skillGroups).map(([group,skills],i)=><article className="skill-card" key={group}><div className="skill-heading"><span>0{i+1}</span><h3>{group}</h3></div><div className="skill-chips">{skills.map(s=><span key={s}>{s}</span>)}</div></article>)}</div></div></section>
      <section className="section achievement-section"><div className="container achievement-wrap"><div><span className="section-kicker">A COUPLE OF MILESTONES</span><h2>Learning happens<br/>best <em>by doing.</em></h2></div><div className="achievement-list">{achievements.map((a,i)=><article key={a}><span>0{i+1}</span><p>{a}</p><ArrowUpRight size={16}/></article>)}</div></div></section>
      <section className="section education-section" id="education"><div className="container"><Head index="05" eyebrow="THE FOUNDATIONS" title="Education &" accent="learning."/><div className="education-grid">{education.map(e=><article className="education-card" key={e.degree}><div className="edu-icon"><GraduationCap size={20}/></div><div><span className="edu-overline">{e.detail}</span><h3>{e.degree}</h3><p>{e.school}</p></div><ArrowUpRight className="edu-arrow" size={16}/></article>)}</div></div></section>
      <section className="section cert-section" id="certifications"><div className="container"><Head index="06" eyebrow="CONTINUOUS LEARNING" title="Courses &" accent="certifications."/><div className="cert-grid">{certifications.map(([name,issuer],i)=><article className="cert-card" key={name}><div className="cert-index">0{i+1}<ArrowUpRight size={15}/></div><div><h3>{name}</h3><p>{issuer}</p></div></article>)}</div></div></section>
      <section className="section profiles-section"><div className="container profile-wrap"><div><Head index="07" eyebrow="FIND ME ONLINE" title="Coding &" accent="profiles."/><p className="profile-blurb">A few places where I share, learn, and keep building.</p></div><div className="profile-cards">{socials.map(({name,href,Icon})=><a key={name} href={href} {...ext} className="profile-card"><span className="profile-icon"><Icon size={19}/></span><span><small>PROFILE</small><strong>{name==='LeetCode'?'Satyam-26':name==='GitHub'?'paradisesatyam':'LinkedIn'}</strong></span><ArrowUpRight size={16}/></a>)}</div></div></section>
      <section className="section contact-section" id="contact"><div className="container"><div className="contact-panel"><div className="contact-copy"><span className="section-kicker">HAVE A PROJECT OR OPPORTUNITY?</span><h2>Let's build<br/>something <em>useful.</em></h2><p>Interested in technology, AI/ML, software development, data analytics, and building practical solutions. Feel free to connect with me.</p><a className="contact-email" href={`mailto:${profile.email}`}>{profile.email}<ArrowUpRight size={16}/></a><div className="contact-detail"><span className="phone-number">{profile.phone}</span><span>·</span><a href={profile.linkedin} {...ext}>LinkedIn ↗</a><span>·</span><a href={profile.github} {...ext}>GitHub ↗</a></div></div><form className="contact-form" onSubmit={send}><label>Name<input required name="name" autoComplete="name" placeholder="Your name"/></label><label>Email<input required name="email" type="email" autoComplete="email" placeholder="you@example.com"/></label><label>Message<textarea required name="message" rows={4} placeholder="What would you like to talk about?"/></label><button className="button primary" type="submit">Send Message <ArrowRight size={16}/></button><span className="form-note">Opens your email app to send directly. No backend required.</span>{sent&&<span role="status" className="form-note">Your email app should open with your message ready.</span>}</form></div></div></section>
    </main>
    <footer className="footer"><div className="container footer-inner"><a className="wordmark" href="#home"><span className="mark">S.</span>Satyam Anand</a><p>AI/ML Enthusiast <span>·</span> Computer Science Student <span>·</span> Builder</p><div className="footer-links"><a href={profile.github} {...ext}>GitHub</a><a href={profile.linkedin} {...ext}>LinkedIn</a><a href={profile.leetcode} {...ext}>LeetCode</a><a href={`mailto:${profile.email}`}>Email</a><a href="/resume.docx" download="Satyam-Anand-Resume.docx">Resume</a></div><small>© 2026 Satyam Anand. All rights reserved.</small></div></footer>
  </div>
}
function Head({index,eyebrow,title,accent}:{index:string;eyebrow:string;title:string;accent:string}){return <div className="section-head"><span className="section-index">{index}</span><div><span className="section-kicker">{eyebrow}</span><h2>{title}<br/><em>{accent}</em></h2></div><span className="head-rule"/></div>}
function Trip(){return <div className="trip-visual"><div className="trip-map"><span className="map-pin pin-a"/><span className="map-pin pin-b"/><span className="map-pin pin-c"/><svg viewBox="0 0 280 130" aria-hidden="true"><path d="M48 94 Q92 26 137 62 T236 34" fill="none" stroke="currentColor" strokeWidth="2" strokeDasharray="5 6"/></svg><span className="map-label">NEW DELHI</span></div><div className="trip-info"><small>YOUR NEXT ADVENTURE</small><b>Explore Rajasthan</b><span>✦ AI curated itinerary</span></div></div>}
function Chart(){return <div className="chart-visual"><div className="chart-head"><span>Revenue overview</span><b>SALES INSIGHTS</b></div><div className="chart-bars">{[34,48,39,64,52,76,58,89,70,100,75,90].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="chart-labels"><span>SALES</span><span>REVENUE</span><span>PROFIT</span><span>TRENDS</span></div><div className="chart-metrics"><span>DATA<strong>Analysis</strong></span><span>VIEW<strong>Dashboard</strong></span></div></div>}
function Planner(){return <div className="planner-visual"><div className="planner-greeting"><small>YOUR WORKSPACE</small><b>Plan a focused day ✳</b></div><div className="planner-task done"><i>✓</i><span><b>Review project notes</b><small>FOCUS SESSION</small></span></div><div className="planner-task"><i/><span><b>Plan the week ahead</b><small>PERSONAL</small></span></div><div className="planner-habit"><span>DAILY HABITS</span><b>◉ ◉ ◉ ◉ ◉ ○ ○</b></div></div>}
